
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oatxqwsmylwagybwqmjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdHhxd3NteWx3YWd5YndxbWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTQwNDcsImV4cCI6MjA1ODU3MDA0N30.JxZaEbAV6w7U5hn19A2mm9Ef-UVdIx1f8eaoPzGHjrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check database connection status
export const checkDatabaseConnection = async () => {
  try {
    // Use a simple health check query that bypasses type checking
    const { error } = await (supabase as any).rpc('get_current_timestamp');
    return !error;
  } catch (error) {
    console.error('Database connection error:', error);
    return false;
  }
};
